name: continuos-deployment
run-name: Deploy do App
on:
    # pull_request:
      #  branches:
       #     - main
    workflow_dispatch:
jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        steps:
                - uses: actions/checkout@v4
                  with:
                    fetch-depth: 0

                - name: Docker Login
                  uses: docker/login-action@v3.4.0
                  with:
                    username: ${{ secrets.DOCKER_USER}}
                    password: ${{ secrets.DOCKER_PASSWORD}}
                    
                - name: Build and push Docker Image
                  uses: docker/build-push-action@v6.15.0
                  with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: gobbozera/devops-ci:latest
                
                - name: Azure WebApp
                  uses: Azure/webapps-deploy@v3.0.1
                  with:
                    app-name: gobbozera-devops-ci
                    publish-profile: ${{ secrets.PUBLISH_PROFILE}}
                    image: gobbozera/devops-ci:latest
